using System;
using System.Collections.Generic;

namespace EFDatabaseFirstDemoApi.Domain.Models;

// This file is generated by the EF Core scaffolding process. It represents the "Todo" table in the database.
public partial class Todo
{
    public int Id { get; set; }

    public string Description { get; set; } = null!;

    public DateOnly? DueDate { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? CompletedAt { get; set; }

    public int CategoryId { get; set; }

    public int StatusId { get; set; }

    public bool IsDeleted { get; set; } // added after the scaffolding

    public virtual Category Category { get; set; } = null!;

    public virtual Status Status { get; set; } = null!;
}
